org.gradle.jvmargs=-Xmx4G -XX:+HeapDumpOnOutOfMemoryError -Dsun.net.client.defaultReadTimeout=120000 -Dsun.net.client.defaultConnectTimeout=60000
android.useAndroidX=true
android.enableJetifier=true
org.gradle.java.home=/Library/Java/JavaVirtualMachines/jdk-17.jdk/Contents/Home
#android.jetifier.blacklist =
android.jetifier.ignorelist=com.player.chat.flutter_chat_app